apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"redis"},"name":"redis","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redis"}},"template":{"metadata":{"labels":{"app":"redis"}},"spec":{"containers":[{"args":["/etc/redis/redis.conf","--requirepass","$(REDIS_PASSWORD)"],"command":["redis-server"],"env":[{"name":"REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"REDIS_PASSWORD","name":"redis-secret"}}}],"image":"redis:7-alpine","livenessProbe":{"exec":{"command":["redis-cli","--no-auth-warning","-a","$(REDIS_PASSWORD)","ping"]},"initialDelaySeconds":30,"periodSeconds":10},"name":"redis","ports":[{"containerPort":6379}],"readinessProbe":{"exec":{"command":["redis-cli","--no-auth-warning","-a","$(REDIS_PASSWORD)","ping"]},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/etc/redis","name":"redis-config-volume"},{"mountPath":"/data","name":"redis-data"}]}],"volumes":[{"configMap":{"name":"redis-config"},"name":"redis-config-volume"},{"name":"redis-data","persistentVolumeClaim":{"claimName":"redis-pvc"}}]}}}}
  creationTimestamp: "2025-05-30T19:23:50Z"
  generation: 1
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "19314"
  uid: 835c93c6-35d1-4686-8baf-3cd0361a367e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - args:
        - /etc/redis/redis.conf
        - --requirepass
        - $(REDIS_PASSWORD)
        command:
        - redis-server
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: redis-secret
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/redis
          name: redis-config-volume
        - mountPath: /data
          name: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-config
        name: redis-config-volume
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-30T19:23:50Z"
    lastUpdateTime: "2025-05-30T19:24:07Z"
    message: ReplicaSet "redis-cd7b9d7bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-30T21:25:58Z"
    lastUpdateTime: "2025-05-30T21:25:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1